image: openjdk:8

cache:
    key: "$CI_BUILD_REF_NAME"

stages:
    - build
    - package
    - deploy

before_script:
    - export MAVEN_USER_HOME=`pwd`/.maven
    - cd server
    - chmod +x mvnw

maven-build:
    stage: build
    script:
        - ./mvnw compile -Dmaven.repo.local=$MAVEN_USER_HOME

maven-deploy:
    stage: deploy
    script:
        - ./mvnw com.heroku.sdk:heroku-maven-plugin:1.1.1:deploy -DskipTests -Dheroku.appName=nk-tree
    artifacts:
        paths:
            - server/target/*.jar
